export const eventAdjectives = [
  "absurd",
  "adorable",
  "amusing",
  "astonishing",
  "awesome",
  "awful",
  "beautiful",
  "bizarre",
  "charming",
  "clever",
  "cool",
  "crazy",
  "cute",
  "dark",
  "disastrous",
  "dramatic",
  "entertaining",
  "fascinating",
  "fun",
  "glamorous",
  "groovy",
  "hilarious",
  "humorous",
  "imaginary",
  "impossible",
  "intelligent",
  "jolly",
  "joyous",
  "kindhearted",
  "laughable",
  "lovely",
  "magical",
  "magnificent",
  "majestic",
  "marvelous",
  "meaningless",
  "mysterious",
  "obscene",
  "outrageous",
  "paranormal",
  "powerful",
  "psychedelic",
  "puzzling",
  "quirky",
  "remarkable",
  "romantic",
  "scary",
  "scandalous",
  "secretive",
  "shocking",
  "spectacular",
  "spiritual",
  "superficial",
  "terrible",
  "terrific",
  "thought-provoking",
  "tremendous",
  "twisted",
  "unexpected",
  "unnatural",
  "wacky",
  "warm",
  "whimsical",
  "wicked",
  "witty",
  "wonderful",
];

export const eventCategory = [
  "sports and games",
  "kings or queens",
  "wars and battles",
  "science",
  "the universe",
  "entertainment",
  "a discovery",
  "love",
  "animals",
  "philosophy",
  "something unexpected",
  "a famous political figure",
  "a famous actor",
  "a famous actress",
  "a famous author",
  "a famous scientist",
  "a famous philosopher",
  "a famous athlete",
  "a fictional character",
  "the ocean",
  "mountains",
  "litterature",
  "historical figures",
  "famous hoaxes",
  "unusual inventions",
  "weird laws",
  "unexplained phenomena",
  "unusual royal ceremonies",
  "fashion trends",
  "medical treatments",
  "famous scandals",
  "jobs and professions",
  "unconventional modes of transportation",
  "peculiar customs and traditions",
  "conspiracy theories",
  "disasters and accidents",
  "foods and delicacies",
  "feuds and rivalries",
  "odd punishments and executions",
  "mysteries",
  "famous escapes and jailbreaks",
  "world records",
  "supernatural occurrences",
];

export const getAdjectivesString = () => {
  const shuffled = [...eventAdjectives].sort(() => 0.5 - Math.random());
  const threeAdj = shuffled.slice(0, 3);
  return `${threeAdj[0]}, ${threeAdj[1]} and ${threeAdj[2]}`;
};

export const getEventCategory = () => {
  return eventCategory[Math.floor(Math.random() * eventCategory.length)];
};
