import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import dayjs from "dayjs";
import advancedFormat from "dayjs/plugin/advancedFormat";

import prisma from "../lib/prisma";

const inter = Inter({ subsets: ["latin"] });
dayjs.extend(advancedFormat);

export default function Home({ fact }: { fact: any }) {
  return (
    <>
      <Head>
        <title>Fun facts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{fact}</div>
    </>
  );
}

export async function getServerSideProps() {
  const fact = await prisma.fact.findFirst({ orderBy: { createdAt: "desc" } });

  return {
    props: {
      fact: fact?.text,
    },
  };
}
